### ISSUE TITLE
Sprinting not working as intended

### ISSUE THREAD

**Issue by WesleyNichols** [ringosham/ToggleSneak#5]
Toggling sprinting only lets you sprint when you're already moving forward. If you stop running the sprinting stops, and you have to toggle it off and on while moving forward to resume a sprint again. The same occurs if you toggle sprinting on while not moving forward - you won't be able to sprint unless you toggle it off and on while moving forward.

**Comment by ringosham** [comment]
Can't reproduce the issue. Can you be a bit more specific on what did you do to cause this?

**Comment by ringosham** [comment]
Closed due to inactivity.
