### ISSUE TITLE
Menu button overrides other mods which place buttons in the same locations (right or left)

### ISSUE THREAD

**Issue by Carson365** [ringosham/ToggleSneak#8]
https://user-images.githubusercontent.com/59584865/107844635-bc829e00-6d9a-11eb-8613-86c15913581e.mp4

The video should speak for itself, but I'm happy to answer any questions.

**Comment by ringosham** [comment]
That's an oversight from the legacy code. It doesn't check if there's a button there or not so it draws over them.
I can add an option so that you can place it in whatever Y-coordinates you want.

**Comment by ringosham** [comment]
On second thought, this might need more changes as there's the consideration of screen size changes
Or.....
Just remove the button altogether. You can always access it via "Mod options" anyway
