### ISSUE TITLE
1.8.9

### ISSUE THREAD

**Issue by KevinKharma1** [ringosham/ToggleSneak#9]
Hey, there is no issue, but can you please make this mod for version 1.8.9? I want to use it when I play Hypixel SkyBlock and I'm not used to hold sneak.

**Comment by ringosham** [comment]
A 1.8.9 version is already made by the original author many years ago

https://www.reddit.com/r/hcfactions/comments/2utdu4/voila_togglesneak_v311_beta_for_forge_18

**Comment by 0uzi** [comment]
The original creators 1.8.9 version requires PlayerAPI. Is it possible to create a 1.8.9 version of this mod that does not require PlayerAPI?

**Comment by ringosham** [comment]
Maybe and maybe not. Regardless, I don't want to rewrite something that isn't broken.

**Comment by 0uzi** [comment]
Would u do it for a scooby snack?
